### ISSUE TITLE
64 bit

### ISSUE THREAD

**Issue by thehotery** [huanrenfeng/7zipDarkmode#4]
Please make 64 bit binary!

**Comment by renfenghuan** [comment]
Well, is that important? the 7zFM is just a UI. When extracting files it uses it's core 7z.exe, as far as I know.

**Comment by itsmeboy0** [comment]
> Well, is that important? the 7zFM is just a UI. When extracting files it uses it's core 7z.exe, as far as I know.

@huanrenfeng Well, 64-bit is better than 32-bit so why not. At least provide it to people on 64-bit machines who want to use a 64-bit binary. Also, Microsoft has already dropped support for Windows 10 on 32-bit systems (Most likely Windows 11 would be only 64-bit as well now).

**Comment by Pachuquero** [comment]
I too think it would be great with a 64-bit version, and many thanks for your efforts so far!

**Comment by huanrenfeng** [comment]
It's an open source project. You can try compile for 64bit first. I'll try it later if I have time.

**Comment by yener90** [comment]
@thehotery  https://github.com/yener90/7zipDarkmode/releases/tag/0.06

forked and published a version for v21.07 & 64bit support

**Comment by ImportTaste** [comment]
It would be handy if there could be a manual activation workflow that could handle the process. 

> @thehotery https://github.com/yener90/7zipDarkmode/releases/tag/0.06
> 
> forked and published a version for v21.07 & 64bit support

Thanks!

**Comment by huanrenfeng** [comment]
Merged! Case close!

**Comment by rollingmoai** [comment]
> @thehotery https://github.com/yener90/7zipDarkmode/releases/tag/0.06
> 
> forked and published a version for v21.07 & 64bit support

@yener90 Mind opening the issues tab on your fork?

**Comment by yener90** [comment]
@itsmeboy0 done
