### ISSUE TITLE
v0.05 is based on a 2019 version of 7zip

### ISSUE THREAD

**Issue by b1k3rdude** [huanrenfeng/7zipDarkmode#5]
Any chance of a version based on the latest 2021 binary?

**Comment by local5805** [comment]
please update to version 21.06 (2021-11-24)

**Comment by huanrenfeng** [comment]
I tested. The current release of 7zipdarkmode file can work for 21.06 64-bit without any problem.

The reason is simple. 7zFM.exe is just a GUI. The real compressing and decompressing work is handled by  7z.exe etc.

I can even say that 7zipdarkmode  can work for any version of 7zip.
