### ISSUE TITLE
please update to version 21.06 (2021-11-24) 64-bit

### ISSUE THREAD

**Issue by local5805** [huanrenfeng/7zipDarkmode#6]
please update to version 21.06 (2021-11-24) 64-bit

**Comment by ImportTaste** [comment]
@huanrenfeng Yes please. I'd also really appreciate it.

**Comment by huanrenfeng** [comment]
I'll see what I can do.

**Comment by huanrenfeng** [comment]
I tested. The current release of 7zipdarkmode file can work for 21.06 64-bit without any problem.

The reason is simple. 7zFM.exe is just a GUI. The real compressing and decompressing work is handled by  7z.exe etc.

I can even say that 7zipdarkmode  can work for any version of 7zip.

**Comment by yener90** [comment]
https://github.com/yener90/7zipDarkmode/releases/tag/0.06

forked and published a version for v21.07 & 64bit support

@ huanrenfeng  if you want, i can push the changes to your fork

**Comment by huanrenfeng** [comment]
> @local5805 @ImportTaste https://github.com/yener90/7zipDarkmode/releases/tag/0.06
> 
> forked and published a version for v21.07 & 64bit support
> 
> @huanrenfeng if you want, i can push the changes to your fork

That's awesome! Submit a PR and I'll merge that! Thank you!

**Comment by huanrenfeng** [comment]
> @local5805 @ImportTaste https://github.com/yener90/7zipDarkmode/releases/tag/0.06
> 
> forked and published a version for v21.07 & 64bit support
> 
> @huanrenfeng if you want, i can push the changes to your fork

Wait, I checked your code for a little bit, it seems that the code is not compatible with old versions?

**Comment by yener90** [comment]
yes its correct. it is based on the newest version. old version was also not compatible with the newest version.

**Comment by huanrenfeng** [comment]
> yes its correct. it is based on the newest version. old version was also not compatible with the newest version. There is also a little difference. Building x64 requires detours x64. If you build x64 you need to name the library detours64.lib

Yeah I know.
Don't worry. I'll just merge it. People can download 0.05 for old versions and 0.06 for new x64 version.

**Comment by huanrenfeng** [comment]
Merged! Case close!
