### ISSUE TITLE
What is the code licensed under?

### ISSUE THREAD

**Issue by natewrench** [huanrenfeng/7zipDarkmode#7]
suggest this license: LGPL v2.1 or later

**Comment by huanrenfeng** [comment]
The code is licensed the same as the original 7-zip code.

I'm not a license expert. But I think the original 7-zip's license requires all projects that edit it to be using the same license.

**Comment by huanrenfeng** [comment]
I checked at https://sourceforge.net/projects/sevenzip/, the GUI part of 7-zip is using LGPL 2.0, so I use the same.
